 output:
 reading item = 1
 reading item = 2
 reading item = 3
 processing item = 1
 processing item = 2
 processing item = 3
 About to write chunk: [1, 2, 3]
 writing item = 1
 writing item = 2
 writing item = 3


 reading item = 4
 reading item = 5
 reading item = 6
 processing item = 4
 processing item = 5
 processing item = 6
 About to write chunk: [4, 5, 6]
 writing item = 4
 Throwing exception on item 5
 processing item = 4       <----- exception during writing caused the processing to start again, even broke the chunks into individual items. Chunk that had errorneous record got broken into seperate process and writes..
 About to write chunk: [4]
 writing item = 4
 processing item = 5
 About to write chunk: [5]
 Throwing exception on item 5
 processing item = 6
 About to write chunk: [6]
 writing item = 6
 reading item = 7
 reading item = 8
 reading item = 9
 processing item = 7
 processing item = 8
 processing item = 9
 About to write chunk: [7, 8, 9]
 writing item = 7
 writing item = 8
 writing item = 9
 reading item = null
